name: Deploy Spring Boot Backend to VPS

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/expense-calculator-backend:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/ExpenseCalculator
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/expense-calculator-backend:latest

            cat <<EOF > docker-compose.yml
            version: '3.8'
            services:
              app:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/expense-calculator-backend:latest
                ports:
                  - "8080:8080"
                depends_on:
                  - db
                environment:
                  DB_URL: db
                  DB_USERNAME: ${{ secrets.DB_USERNAME }}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

              db:
                image: postgres:13
                environment:
                  POSTGRES_DB: budget_db
                  POSTGRES_USER: ${{ secrets.DB_USERNAME }}
                  POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
            EOF

            docker compose down || true
            docker compose up -d --remove-orphans

